filter:
    excluded_paths:
        - vendor/*
        - tests/*
        - docs/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 800
        runs: 2


build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
