filter:
    excluded_paths:
        - vendor/*
        - tests/*
        - doc/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 800
        runs: 2

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    -
                         command: 'vendor/bin/simple-phpunit -v --coverage-clover build/clover.xml  --exclude-group installation'
                         environment: { SYMFONY_PHPUNIT_VERSION: '6.5' }
                         coverage:
                              file: 'build/clover.xml'
                              format: 'clover'
