filter:
    excluded_paths:
        - vendor/*
        - tests/*
        - doc/*

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 1200
        runs: 2
