#!/usr/bin/env php
<?php

/*
 * This file is part of the FOSCKEditor Bundle.
 *
 * (c) 2018 - present  Friends of Symfony
 * (c) 2009 - 2017     Eric GELOEN <geloen.eric@gmail.com>
 *
 * For the full copyright and license information, please read the LICENSE
 * file that was distributed with this source code.
 */

use FOS\CKEditorBundle\Command\CKEditorInstallerCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

require_once __DIR__.'/../../vendor/autoload.php';

$application = new Application();
$application->add(new CKEditorInstallerCommand());
$application->run(new ArgvInput());
